project:
  type: book
  render:
    - index.qmd 
  output-dir: docs
book:
  title: Statistical Computing Prac 1
  author: "Raphaela Azar"
  sidebar:
    border: true
    background: light
    position: right
    output: 
    html: true
  navbar:
    search: true
    background: light
  chapters:
    - index.qmd
    - Question1.qmd
    - Question2.qmd
    - Question3.qmd
    - Question4.qmd
    - function_summary(lm()).qmd
format:
  html:
    theme: cosmo
